version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python myproject/manage.py runserver 0.0.0.0:9000